spring:
  kafka:
    # The address of the Kafka broker that the application will connect to
    bootstrap-servers: kafka:9092
    
    consumer:
      # The consumer group ID for the Kafka consumers in this application
      group-id: stock 
      
      # When no offset is available, start reading from the earliest message
      auto-offset-reset: earliest
      
      # Deserializer class for the key in Kafka messages (converts byte data to String)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
      # Deserializer class for the value in Kafka messages (converts byte data to String)
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Custom app-level Kafka configuration
app:
  kafka:
    topic: orders_topic
